### ISSUE TITLE
TypeError: prepare_model_for_int8_training() got an unexpected keyword argument 'output_embedding_layer_name'

### ISSUE THREAD

**Issue by shaybek** [Vaibhavs10/fast-whisper-finetuning#1]
TypeError: prepare_model_for_int8_training() got an unexpected keyword argument 'output_embedding_layer_name'

**Comment by Houss3m** [comment]
in this line of code: model = prepare_model_for_int8_training(model, output_embedding_layer_name="proj_out1")
TypeError: prepare_model_for_int8_training() got an unexpected keyword argument 'output_embedding_layer_name'

**Comment by Houss3m** [comment]
> TypeError: prepare_model_for_int8_training() got an unexpected keyword argument 'output_embedding_layer_name'

have you solved it?

**Comment by Jack-du-ubc** [comment]
Delete the argument, or using model = prepare_model_for_kbit_training(model, use_gradient_checkpointing= True).

**Comment by Vaibhavs10** [comment]
Yes! Sorry, I'll update this guide in the next two weeks to support QLoRA, but for now, deleting the argument as mentioned by @Jack-du-ubc should do the trick.

Really sorry for the delay in getting back to you.

Closing this now, but feel free to open it again, if you face issues.
