### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cget_col_row_stats'

### ISSUE THREAD

**Issue by masapasa** [Vaibhavs10/fast-whisper-finetuning#2]
Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:4                                                                                    │
│                                                                                                  │
│ /home/Startupcolors/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py:2777  │
│ in from_pretrained                                                                               │
│                                                                                                  │
│   2774 │   │   │   │   mismatched_keys,                                                          │
│   2775 │   │   │   │   offload_index,                                                            │
│   2776 │   │   │   │   error_msgs,                                                               │
│ ❱ 2777 │   │   │   ) = cls._load_pretrained_model(                                               │
│   2778 │   │   │   │   model,                                                                    │
│   2779 │   │   │   │   state_dict,                                                               │
│   2780 │   │   │   │   loaded_state_dict_keys,  # XXX: rename?                                   │
│                                                                                                  │
│ /home/Startupcolors/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py:3118  │
│ in _load_pretrained_model                                                                        │
│                                                                                                  │
│   3115 │   │   │   │   )                                                                         │
│   3116 │   │   │   │                                                                             │
│   3117 │   │   │   │   if low_cpu_mem_usage:                                                     │
│ ❱ 3118 │   │   │   │   │   new_error_msgs, offload_index, state_dict_index = _load_state_dict_i  │
│   3119 │   │   │   │   │   │   model_to_load,                                                    │
│   3120 │   │   │   │   │   │   state_dict,                                                       │
│   3121 │   │   │   │   │   │   loaded_keys,                                                      │
│                                                                                                  │
│ /home/Startupcolors/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py:710   │
│ in _load_state_dict_into_meta_model                                                              │
│                                                                                                  │
│    707 │   │   │   │   fp16_statistics = None                                                    │
│    708 │   │   │                                                                                 │
│    709 │   │   │   if "SCB" not in param_name:                                                   │
│ ❱  710 │   │   │   │   set_module_8bit_tensor_to_device(                                         │
│    711 │   │   │   │   │   model, param_name, param_device, value=param, fp16_statistics=fp16_s  │
│    712 │   │   │   │   )                                                                         │
│    713                                                                                           │
│                                                                                                  │
│ /home/Startupcolors/miniconda3/lib/python3.10/site-packages/transformers/utils/bitsandbytes.py:7 │
│ 8 in set_module_8bit_tensor_to_device                                                            │
│                                                                                                  │
│    75 │   │   │   │   │   │   )                                                                  │
│    76 │   │   │   else:                                                                          │
│    77 │   │   │   │   new_value = torch.tensor(value, device="cpu")                              │
│ ❱  78 │   │   │   new_value = bnb.nn.Int8Params(new_value, requires_grad=False, has_fp16_weigh   │
│    79 │   │   │   module._parameters[tensor_name] = new_value                                    │
│    80 │   │   │                                                                                  │
│    81 │   │   │   if fp16_statistics is not None:                                                │
│                                                                                                  │
│ /home/Startupcolors/miniconda3/lib/python3.10/site-packages/bitsandbytes/nn/modules.py:196 in to │
│                                                                                                  │
│   193 │   │   │   and device.type == "cuda"                                                      │
│   194 │   │   │   and self.data.device.type == "cpu"                                             │
│   195 │   │   ):                                                                                 │
│ ❱ 196 │   │   │   return self.cuda(device)                                                       │
│   197 │   │   else:                                                                              │
│   198 │   │   │   new_param = Int8Params(                                                        │
│   199 │   │   │   │   super().to(                                                                │
│                                                                                                  │
│ /home/Startupcolors/miniconda3/lib/python3.10/site-packages/bitsandbytes/nn/modules.py:160 in    │
│ cuda                                                                                             │
│                                                                                                  │
│   157 │   │   │   # we store the 8-bit rows-major weight                                         │
│   158 │   │   │   # we convert this weight to the turning/ampere weight during the first infer   │
│   159 │   │   │   B = self.data.contiguous().half().cuda(device)                                 │
│ ❱ 160 │   │   │   CB, CBt, SCB, SCBt, coo_tensorB = bnb.functional.double_quant(B)               │
│   161 │   │   │   del CBt                                                                        │
│   162 │   │   │   del SCBt                                                                       │
│   163 │   │   │   self.data = CB                                                                 │
│                                                                                                  │
│ /home/Startupcolors/miniconda3/lib/python3.10/site-packages/bitsandbytes/functional.py:1616 in   │
│ double_quant                                                                                     │
│                                                                                                  │
│   1613 │   │   rows = A.shape[0]                                                                 │
│   1614 │                                                                                         │
│   1615 │   if row_stats is None or col_stats is None:                                            │
│ ❱ 1616 │   │   row_stats, col_stats, nnz_row_ptr = get_colrow_absmax(                            │
│   1617 │   │   │   A, threshold=threshold                                                        │
│   1618 │   │   )                                                                                 │
│   1619                                                                                           │
│                                                                                                  │
│ /home/Startupcolors/miniconda3/lib/python3.10/site-packages/bitsandbytes/functional.py:1505 in   │
│ get_colrow_absmax                                                                                │
│                                                                                                  │
│   1502 │                                                                                         │
│   1503 │   prev_device = pre_call(A.device)                                                      │
│   1504 │   is_on_gpu([A, row_stats, col_stats, nnz_block_ptr])                                   │
│ ❱ 1505 │   lib.cget_col_row_stats(ptrA, ptrRowStats, ptrColStats, ptrNnzrows, ct.c_float(thresh  │
│   1506 │   post_call(prev_device)                                                                │
│   1507 │                                                                                         │
│   1508 │   if threshold > 0.0:                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'cget_col_row_stats'

**Comment by Helene-Maxcici** [comment]
Which CUDA version are you using?

**Comment by Vaibhavs10** [comment]
@masapasa - This should be fixed with the latest version of `bnb` and `peft`, do let me know if you face the same issues still.
