### ISSUE TITLE
TypeError: prepare_model_for_kbit_training() got an unexpected keyword argument 'output_embedding_layer_name'

### ISSUE THREAD

**Issue by ILG2021** [Vaibhavs10/fast-whisper-finetuning#6]
maybe prepare_model_for_8bit_training is deprecated.

**Comment by nrshoudi** [comment]
Hey
I faced the same issue. 
Did you find any solution?

**Comment by ILG2021** [comment]
> Hey I faced the same issue. Did you find any solution?

prepare_model_for_kbit_training is the new function.

**Comment by bastiansurya77** [comment]
Did it had solution to it?, I also face the same problems

**Comment by QvQKing** [comment]
from peft import prepare_model_for_int8_training, prepare_model_for_kbit_training

#model = prepare_model_for_int8_training(model, output_embedding_layer_name="proj_out")
model = prepare_model_for_kbit_training(model)
Using the new function  prepare_model_for_kbit_training(model) can solve this problem.
